<table class="table table-bordered span7">
	<tr>
		<td style="font-size:20px">
			Lista de personas
			<a href="/sandro/nuevo" class="btn btn-success">nuevo</a>
		</td>
	</tr>
	<tr>
		<td>
			<?php
			if ($this->dato) {	?>				
			<table>
				<th>Codigo</th>
				<th>Nombre</th>
				<th>Telefono</th>
				<?php
					foreach ($this->dato as $datos){
				?>
				<tr>
					<td><?php echo $datos['pid']?></td>
					<td><?php echo $datos['nom']?></td>
					<td><?php echo $datos['tel']?></td>
					<td><a href="/sandro/modificar/id/<?php echo $datos['pid']?>">Modificar</a></td>
					<td><a class='soy' href="#" pid="<?php echo $datos['pid']?>">Eliminar</a>
				</td>
					<td></td>

				</tr>
				<?php 
					}
				}
				?>	
			</table>
		</td>
	</tr>	

</table>

<script>
	$('.soy').click(function(){
		var $this =$(this);
		var pid=$this.attr('pid'); 
		var respons=confirm('desea eliminar');
		if (respons) 
			{
				$this.attr('href','/sandro/eliminar/pid/'+pid);
			};
		});
</script>	
<a id='hola' href="#"></a>
<script type="text/javascript">
$("#hola").click(function(){
	alert("Alerta");
});
</script>
