<form method="POST" action="/Sandro/modificar">

	<label>ingrese codigo:</label>
	<?php echo $this->frmPersona->pid?>

	<label>ingrese apellido paterno:</label>
	<?php echo $this->frmPersona->apat?>

	<label>ingrese apellido materno:</label>
	<?php echo $this->frmPersona->amat?>

	<label>ingrese nombre:</label>
	<?php echo $this->frmPersona->nom?>

	<label>ingrese telefono:</label>
	<?php echo $this->frmPersona->tel?>

	<label>ingrese direccion:</label>
	<?php echo $this->frmPersona->dir?>

	<?php echo $this->frmPersona->Guardar?>

</form>