<form method="POST">

	<label>Ingrese codigo:</label>
	<?php echo $this->frmAutos->aid?>

	<label>Ingrese Nombre:</label>
	<?php echo $this->frmAutos->nombre?>

	<label>Ingrese Descripcion:</label>
	<?php echo $this->frmAutos->descripcion?>

	<label>Ingrese Color:</label>
	<?php echo $this->frmAutos->color?>

	<label>Ingrese Pais Procedencia:</label>
	<?php echo $this->frmAutos->pais_proc?>

	<?php echo $this->frmAutos->Guardar?>

</form>